---
title: "life_expectancy"
output: html_document
---

```{r libraries, include=FALSE}
# Required Libraries

#install.packages("tidyverse")
#install.packages("naniar")
#install.packages("gridExtra")
install.packages("corrplot")

library(tidyverse)
library(naniar)
library(gridExtra)
library(corrplot)
```


```{r dataload}
# Read csv from project dir

life_df <- read_csv("data/LifeExpectancyData.csv")

life_df <- 
  life_df %>%
  filter(Year == 2014)

head(life_df)
```

```{r}

for (i in 1:length(names(life_df))) {
  ifelse(
  grep(" ",names(life_df)[i]) == TRUE,
  names(life_df)[i] <- gsub(" ", "_", names(life_df)[i]),
  next
  )
}

names(life_df)

```








```{r}
# Summary of data
summary(life_df)


# Quick Viz to see where NAs 
gg_miss_var(life_df)

```

```{r}
life_df %>%
  filter(
    Status == "Developed"
  ) %>%
    ggplot() +
    geom_col(
      aes(
        x = reorder(Country, Life_expectancy),
        y = Life_expectancy,
        fill = Status
      )
    ) +
    coord_flip() +
    theme(
      axis.text.y = element_text(size=6),
    )


```


```{r}
life_df %>%
  filter(
    Status == "Developing"
  ) %>%
    ggplot() +
    geom_col(
      aes(
        x = reorder(Country, Life_expectancy),
        y = Life_expectancy,
        fill = Status
      )
    ) +
    coord_flip() +
    theme(
      axis.text.y = element_text(size=2),
    )
```



```{r}

# pairs(life_df[,-(1:3)])


```







```{r}
# Need to resolve NAs

corrplot(
  cor(life_df[,-(1:3)]), 
  type="upper"
  )
```
















