---
title: "DS6372_Project1_LifeExpectancy"
author: "Jason Rupp, Daanesh Ibrahim and Bala Dakshinamoorthi"
date: "6/13/2020"
output: html_document
---

```{r setup, include=FALSE}
library(pander)

```

## Introduction Required

In the global health community, a common measure of the health status of a nation is the life expectancy of a person at birth. This measure can tell a lot about the strength of the nation's health care system and there are great many contributing factors which go into determining this measure. The difficulty with determining life expectancy is that if it is a measure of a population that is living, it will always an estimate. The actual life span or expected life span of a population will take a number of years to determine, as the group would have to expire. To further complicate matters, these estimates are based on whether the conditions of a health system or the relative health status of a nation will remain constant. Due to these factors, we must rely on statistical methods to derive these measures, as they can be very useful to the global health community. The purpose of this project is to use a set of data with roughly 20 features related to the health care systems of 193 nations to develop statistical models which may best predict the life expectancy of a nation. We will begin by presenting the data then briefly explain steps used to evaluate said data for model selection.


## Data Description  Required

The data set used for this project was obtained from Kaggle, the link for which can be found in the appendix accompanied with a full description of each feature as described on the website for quick reference. The overall data set contained 22 columns, 1 column that identified the country, 1 which held the life expectancy of the country and 20 features related to the health and economic status of 193 nations from a 15 year period, between 2000-2015. The user that posted the data claims to have obtained the health related features from the Global Health Observatory (GHO) data repository under World Health Organization (WHO) and the economic features from the United Nations website. Additionally, this user did note that it appeared to be free of errors, though there were missing values in some of the features. The missing values will addressed later in the discussion. Most of the attributes are self explanatory with regard to the value and the unit, here are some key points about the data the will bring context into interpretation of the models further in the paper. Polio, Hepatitis B, Diphtheria (Diphtheria tetanus toxoid and pertussis - DTP3) refer to the immunization coverage among 1-year-olds (%). The infant, under-five, HIV/AIDS features refer to the number of deaths per 1000 population; HIV/AIDS in the age range of 0-4 years. Adult Mortality is the probability  of both sexes of dying between 15 and 60 years per 1000 population. Measles is the number of reported cases per 1000 population. One thing of note that was noticed about the data set description was that the "thinness 1-19 years" feature said in the description that it was the	prevalence of thinness among children and adolescents for Age **10** to 19 (%), so this is a bit of an ambigious attribute which could refer to either age, either way, it was noted an analysis continued.



## Exploratory Data Analysis Required

Life Expenctancy has a strong positive correlation with Schooling 
and Income_composition_of_resources.

Life_expectancy has a strong negative correlation with Adult_Mortality
which is understandable since if mortality rate in adults is high, Life
exepctancy would be lower.

Population and Measels show almost no correlation with Life_Expectancy.
infant_deaths and under.five_deaths have a correlation of 1 (100%) which would
tell us that there is multicollinearity between them. We should drop one of the
variables, and I believe under 5 deaths should be dropped. 

Hepatitis.B has the Min Value and 1st Quartile difference of 76 which is too high (Factor?)
Polio has the Min value and 1st QUartile difference of 70 which is too high (Factor?)
Diphtheria has the min value and 1st quartile difference of 78 which is too high (Factor?)


According to the boxplots, the distribution of higher life_expectancy resides
in the developed countries, with the plot even showing that the median for developed
countries (2nd Quartile) beind skewed higher towards the 3rd quartile

## Addressing Objective 1:

### Restatement of Problem and the overall approach to solve it Required

Objective 1: Display the ability to build regression models using the skills and discussions from Unit 1 and 2 with the purpose of identifying key relationships, interpreting those relationships, and making good predictions.   

- Build a model with the main goal to identify key relationships and is highly interpretable.  Perform your regression analysis and report the predictive ability of your model using a test set or some other means through CV.  Be sure to provide metrics if you compare multiple models.

- Provide interpretation of the regression coefficients in the model including hypothesis testing, interpretation of regression coefficients, and confidence intervals. It’s also good to mention the Practical vs Statistical significance of the predictors.

- Fit a second model with the goal to produce the best predictions possible.  Interpretation is no longer important so you can get as complicated as you like.  Use feature selection techniques to avoid under/over fitting.  Compare this model with your first, highly interpretable model, and comment on if this second model brings additional value or the first model is preferred.






## Model Selection Required
### Type of Selection
##### Options: 
            - LASSO, 
            - RIDGE, 
            - ELASTIC NET, 
            - Stepwise, 
            - Forward, 
            - Backward,  
            - Manual / Intuition,
			      - A mix of all of the above.  	

## Checking Assumptions Required
### Residual Plots
### Influential point analysis (Cook’s D and Leverage)

### Compare Competing Models Required
#### Via:  Training and test set split or CV
#### Possible Metrics: ASE (Required), AIC, BIC, adj R2, are all welcomed additions
	
## Parameter Interpretation (Simple model only)
#### Interpretation 
#### Confidence Intervals

             Additional Details on a more complicated regression model 

## Objective 2 Deliverable 

Objective 2 (New):  As mentioned before the advantages of regression is the interpretation of the model produced.  It also works very well when the number of predictors is large and the sample size is small.  Disadvantages to regression is the fact that not all data sets are going to yield “linear” relationships.  If the relationship is quite complex, it will be difficult to fit a good model without a lot of clever engineering of new predictor variables.  
Nonparameteric regression models are models which do not assume the residuals follow any distribution and do not assume any sort of “linear” structure on what the trend between the response and the predictors could be.  For Objective 2, I want you to use the ISLR text book and read up on one nonparametric technique.  I want you to select from k-nearest neighbors’ regression or regression trees.  Splines could also be a topic but personally I think k-nn or trees would be much easier to digest for a short turn around project such as this. After reading up on this topic, I want you to use a set of predictors used from your previous linear regression models and fit your nonparametric model to the data, keeping in mind what the particular model calls for in terms of what type of predictors can be used and parameters that control for model complexity.  The ISLR book provides code at the end of each chapter and I will also provide a small script for you to have so you’re not starting from scratch.  In your write up after the regression models, I want you to include a small section that includes the following:

1.	A brief description of your nonparametric model’s strategy to make a prediction.  Include Pros and Cons.
2.	Provide any additional details that you feel might be necessary to report.
3.	Report the test ASE using this nonparametric model so we can see how well it does compared to regression.

	
## Final conclusions from the analyses of Objective 1’s interpretable model and include comments on what model would be recommended if prediction was the only goal (comparing all models considered). 

In addition to the overall conclusions, feel free to include additional insights or concerns gleaned from the analysis.  What needs to be done next or how could we do it better next time or if we had more time?

## Appendix 
Well commented SAS/R Code
 Graphics and summary tables (Can be placed in the appendix or in the written report itself.)
 
Link to the dataset:
https://www.kaggle.com/kumarajarshi/life-expectancy-who
 
STRAIGHT FROM KAGGLE

About this file
The Global Health Observatory (GHO) data repository under World Health Organization (WHO) keeps track of the health status as well as many other related factors for all countries The datasets are made available to public for the purpose of health data analysis. The dataset related to life expectancy, health factors for 193 countries has been collected from the same WHO data repository website and its corresponding economic data was collected from United Nation website. Among all categories of health-related factors only those critical factors were chosen which are more representative. It has been observed that in the past 15 years , there has been a huge development in health sector resulting in improvement of human mortality rates especially in the developing nations in comparison to the past 30 years. Therefore, in this project we have considered data from year 2000-2015 for 193 countries for further analysis. The individual data files have been merged together into a single dataset. On initial visual inspection of the data showed some missing values. As the datasets were from WHO, we found no evident errors. Missing data was handled in R software by using Missmap command. The result indicated that most of the missing data was for population, Hepatitis B and GDP. The missing data were from less known countries like Vanuatu, Tonga, Togo,Cabo Verde etc. Finding all data for these countries was difficult and hence, it was decided that we exclude these countries from the final model dataset. The final merged file(final dataset) consists of 22 Columns and 2938 rows which meant 20 predicting variables. All predicting variables was then divided into several broad categories:Immunization related factors, Mortality factors, Economical factors and Social factors.

The following descriptions attached to these features are directly from the kaggle website.

Table: Full Data Description


|                   Feature                 |      Description                                                                                       |
|:------------------------------------------|:-------------------------------------------------------------------------------------------------------|
| Country	                                  |Country                                                                                                 |
| Year	                                    |Year                                                                                                    |
| Status	                                  |Developed or Developing status                                                                          |
| Life expectancy                           |Life Expectancy in age                                                                                  |
| Adult Mortality                           |Adult Mortality Rates of both sexes (probability of dying between 15 and 60 years per 1000 population)  |
| infant deaths  	                          |Number of Infant Deaths per 1000 population                                                             | 
| Alcohol		                                |Alcohol, recorded per capita (15+) consumption (in litres of pure alcohol)                              | 
| percentage expenditure	                  |Expenditure on health as a percentage of Gross Domestic Product per capita(%)                           |
| Hepatitis B                               |Hepatitis B (HepB) immunization coverage among 1-year-olds (%)                                          |
| Measles 	                                |Measles - number of reported cases per 1000 population                                                  |  
| BMI 	                                    |Average Body Mass Index of entire population                                                            |  
| under-five deaths 	                      |Number of under-five deaths per 1000 population                                                         |  
| Polio	                                    |Polio (Pol3) immunization coverage among 1-year-olds (%)                                                |  
| Total expenditure	                        |General government expenditure on health as a percentage of total government expenditure (%)            |    
| Diphtheria 	                              |Diphtheria tetanus toxoid and pertussis (DTP3) immunization coverage among 1-year-olds (%)              |  
| HIV/AIDS	                                |Deaths per 1 000 live births HIV/AIDS (0-4 years)                                                       |   
| GDP	                                      |Gross Domestic Product per capita (in USD)                                                              |
| Population	                              |Population of the country                                                                               |   
| thinness 1-19 years	                      |Prevalence of thinness among children and adolescents for Age 10 to 19 (%)                             |  
| thinness 5-9 years	                      |Prevalence of thinness among children for Age 5 to 9(%)                                                 |      
| Income composition of resources	          |Human Development Index in terms of income composition of resources (index ranging from 0 to 1)         | 
| Schooling                                 |Number of years of Schooling(years)                                                                     |    





  
